//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreExtractorResultOfExtractor")
#ifdef RESTRICT_OrgAssertjCoreExtractorResultOfExtractor
#define INCLUDE_ALL_OrgAssertjCoreExtractorResultOfExtractor 0
#else
#define INCLUDE_ALL_OrgAssertjCoreExtractorResultOfExtractor 1
#endif
#undef RESTRICT_OrgAssertjCoreExtractorResultOfExtractor

#if !defined (OrgAssertjCoreExtractorResultOfExtractor_) && (INCLUDE_ALL_OrgAssertjCoreExtractorResultOfExtractor || defined(INCLUDE_OrgAssertjCoreExtractorResultOfExtractor))
#define OrgAssertjCoreExtractorResultOfExtractor_

#define RESTRICT_OrgAssertjCoreApiIterableExtractor 1
#define INCLUDE_OrgAssertjCoreApiIterableExtractor 1
#include "OrgAssertjCoreApiIterableExtractor.h"

@interface OrgAssertjCoreExtractorResultOfExtractor : NSObject < OrgAssertjCoreApiIterableExtractor >

#pragma mark Public

- (id)extractWithId:(id)input;

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)methodName;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgAssertjCoreExtractorResultOfExtractor)

FOUNDATION_EXPORT void OrgAssertjCoreExtractorResultOfExtractor_initWithNSString_(OrgAssertjCoreExtractorResultOfExtractor *self, NSString *methodName);

FOUNDATION_EXPORT OrgAssertjCoreExtractorResultOfExtractor *new_OrgAssertjCoreExtractorResultOfExtractor_initWithNSString_(NSString *methodName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCoreExtractorResultOfExtractor *create_OrgAssertjCoreExtractorResultOfExtractor_initWithNSString_(NSString *methodName);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreExtractorResultOfExtractor)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreExtractorResultOfExtractor")
