//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OrgAssertjCoreErrorBasicErrorMessageFactory.h"
#include "OrgAssertjCoreErrorErrorMessageFactory.h"
#include "OrgAssertjCoreErrorShouldBeLess.h"
#include "OrgAssertjCoreInternalComparisonStrategy.h"
#include "OrgAssertjCoreInternalStandardComparisonStrategy.h"
#include "java/lang/Comparable.h"

@interface OrgAssertjCoreErrorShouldBeLess ()

- (instancetype)initWithJavaLangComparable:(id<JavaLangComparable>)actual
                    withJavaLangComparable:(id<JavaLangComparable>)other
withOrgAssertjCoreInternalComparisonStrategy:(id<OrgAssertjCoreInternalComparisonStrategy>)comparisonStrategy;

@end

__attribute__((unused)) static void OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(OrgAssertjCoreErrorShouldBeLess *self, id<JavaLangComparable> actual, id<JavaLangComparable> other, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

__attribute__((unused)) static OrgAssertjCoreErrorShouldBeLess *new_OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(id<JavaLangComparable> actual, id<JavaLangComparable> other, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgAssertjCoreErrorShouldBeLess *create_OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(id<JavaLangComparable> actual, id<JavaLangComparable> other, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

@implementation OrgAssertjCoreErrorShouldBeLess

+ (id<OrgAssertjCoreErrorErrorMessageFactory>)shouldBeLessWithJavaLangComparable:(id<JavaLangComparable>)actual
                                                          withJavaLangComparable:(id<JavaLangComparable>)other {
  return OrgAssertjCoreErrorShouldBeLess_shouldBeLessWithJavaLangComparable_withJavaLangComparable_(actual, other);
}

+ (id<OrgAssertjCoreErrorErrorMessageFactory>)shouldBeLessWithJavaLangComparable:(id<JavaLangComparable>)actual
                                                          withJavaLangComparable:(id<JavaLangComparable>)other
                                    withOrgAssertjCoreInternalComparisonStrategy:(id<OrgAssertjCoreInternalComparisonStrategy>)comparisonStrategy {
  return OrgAssertjCoreErrorShouldBeLess_shouldBeLessWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(actual, other, comparisonStrategy);
}

- (instancetype)initWithJavaLangComparable:(id<JavaLangComparable>)actual
                    withJavaLangComparable:(id<JavaLangComparable>)other
withOrgAssertjCoreInternalComparisonStrategy:(id<OrgAssertjCoreInternalComparisonStrategy>)comparisonStrategy {
  OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(self, actual, other, comparisonStrategy);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgAssertjCoreErrorErrorMessageFactory;", 0x9, 0, 1, -1, 2, -1, -1 },
    { NULL, "LOrgAssertjCoreErrorErrorMessageFactory;", 0x9, 0, 3, -1, 4, -1, -1 },
    { NULL, NULL, 0x2, -1, 3, -1, 5, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(shouldBeLessWithJavaLangComparable:withJavaLangComparable:);
  methods[1].selector = @selector(shouldBeLessWithJavaLangComparable:withJavaLangComparable:withOrgAssertjCoreInternalComparisonStrategy:);
  methods[2].selector = @selector(initWithJavaLangComparable:withJavaLangComparable:withOrgAssertjCoreInternalComparisonStrategy:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "shouldBeLess", "LJavaLangComparable;LJavaLangComparable;", "<T::Ljava/lang/Comparable<-TT;>;>(TT;TT;)Lorg/assertj/core/error/ErrorMessageFactory;", "LJavaLangComparable;LJavaLangComparable;LOrgAssertjCoreInternalComparisonStrategy;", "<T::Ljava/lang/Comparable<-TT;>;>(TT;TT;Lorg/assertj/core/internal/ComparisonStrategy;)Lorg/assertj/core/error/ErrorMessageFactory;", "(Ljava/lang/Comparable<*>;Ljava/lang/Comparable<*>;Lorg/assertj/core/internal/ComparisonStrategy;)V" };
  static const J2ObjcClassInfo _OrgAssertjCoreErrorShouldBeLess = { "ShouldBeLess", "org.assertj.core.error", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_OrgAssertjCoreErrorShouldBeLess;
}

@end

id<OrgAssertjCoreErrorErrorMessageFactory> OrgAssertjCoreErrorShouldBeLess_shouldBeLessWithJavaLangComparable_withJavaLangComparable_(id<JavaLangComparable> actual, id<JavaLangComparable> other) {
  OrgAssertjCoreErrorShouldBeLess_initialize();
  return create_OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(actual, other, OrgAssertjCoreInternalStandardComparisonStrategy_instance());
}

id<OrgAssertjCoreErrorErrorMessageFactory> OrgAssertjCoreErrorShouldBeLess_shouldBeLessWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(id<JavaLangComparable> actual, id<JavaLangComparable> other, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy) {
  OrgAssertjCoreErrorShouldBeLess_initialize();
  return create_OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(actual, other, comparisonStrategy);
}

void OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(OrgAssertjCoreErrorShouldBeLess *self, id<JavaLangComparable> actual, id<JavaLangComparable> other, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy) {
  OrgAssertjCoreErrorBasicErrorMessageFactory_initWithNSString_withNSObjectArray_(self, @"\nExpecting:\n <%s>\nto be less than:\n <%s> %s", [IOSObjectArray arrayWithObjects:(id[]){ actual, other, comparisonStrategy } count:3 type:NSObject_class_()]);
}

OrgAssertjCoreErrorShouldBeLess *new_OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(id<JavaLangComparable> actual, id<JavaLangComparable> other, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy) {
  J2OBJC_NEW_IMPL(OrgAssertjCoreErrorShouldBeLess, initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_, actual, other, comparisonStrategy)
}

OrgAssertjCoreErrorShouldBeLess *create_OrgAssertjCoreErrorShouldBeLess_initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_(id<JavaLangComparable> actual, id<JavaLangComparable> other, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy) {
  J2OBJC_CREATE_IMPL(OrgAssertjCoreErrorShouldBeLess, initWithJavaLangComparable_withJavaLangComparable_withOrgAssertjCoreInternalComparisonStrategy_, actual, other, comparisonStrategy)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgAssertjCoreErrorShouldBeLess)
