//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreInternalLongs")
#ifdef RESTRICT_OrgAssertjCoreInternalLongs
#define INCLUDE_ALL_OrgAssertjCoreInternalLongs 0
#else
#define INCLUDE_ALL_OrgAssertjCoreInternalLongs 1
#endif
#undef RESTRICT_OrgAssertjCoreInternalLongs

#if !defined (OrgAssertjCoreInternalLongs_) && (INCLUDE_ALL_OrgAssertjCoreInternalLongs || defined(INCLUDE_OrgAssertjCoreInternalLongs))
#define OrgAssertjCoreInternalLongs_

#define RESTRICT_OrgAssertjCoreInternalNumbers 1
#define INCLUDE_OrgAssertjCoreInternalNumbers 1
#include "OrgAssertjCoreInternalNumbers.h"

@class JavaLangLong;
@protocol OrgAssertjCoreInternalComparisonStrategy;

@interface OrgAssertjCoreInternalLongs : OrgAssertjCoreInternalNumbers

#pragma mark Public

- (instancetype)initWithOrgAssertjCoreInternalComparisonStrategy:(id<OrgAssertjCoreInternalComparisonStrategy>)comparisonStrategy;

+ (OrgAssertjCoreInternalLongs *)instance;

#pragma mark Protected

- (JavaLangLong *)zero;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(OrgAssertjCoreInternalLongs)

FOUNDATION_EXPORT OrgAssertjCoreInternalLongs *OrgAssertjCoreInternalLongs_instance();

FOUNDATION_EXPORT void OrgAssertjCoreInternalLongs_init(OrgAssertjCoreInternalLongs *self);

FOUNDATION_EXPORT OrgAssertjCoreInternalLongs *new_OrgAssertjCoreInternalLongs_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCoreInternalLongs *create_OrgAssertjCoreInternalLongs_init();

FOUNDATION_EXPORT void OrgAssertjCoreInternalLongs_initWithOrgAssertjCoreInternalComparisonStrategy_(OrgAssertjCoreInternalLongs *self, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

FOUNDATION_EXPORT OrgAssertjCoreInternalLongs *new_OrgAssertjCoreInternalLongs_initWithOrgAssertjCoreInternalComparisonStrategy_(id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCoreInternalLongs *create_OrgAssertjCoreInternalLongs_initWithOrgAssertjCoreInternalComparisonStrategy_(id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreInternalLongs)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreInternalLongs")
