//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreErrorShouldNotExist")
#ifdef RESTRICT_OrgAssertjCoreErrorShouldNotExist
#define INCLUDE_ALL_OrgAssertjCoreErrorShouldNotExist 0
#else
#define INCLUDE_ALL_OrgAssertjCoreErrorShouldNotExist 1
#endif
#undef RESTRICT_OrgAssertjCoreErrorShouldNotExist

#if !defined (OrgAssertjCoreErrorShouldNotExist_) && (INCLUDE_ALL_OrgAssertjCoreErrorShouldNotExist || defined(INCLUDE_OrgAssertjCoreErrorShouldNotExist))
#define OrgAssertjCoreErrorShouldNotExist_

#define RESTRICT_OrgAssertjCoreErrorBasicErrorMessageFactory 1
#define INCLUDE_OrgAssertjCoreErrorBasicErrorMessageFactory 1
#include "OrgAssertjCoreErrorBasicErrorMessageFactory.h"

@class JavaIoFile;
@protocol OrgAssertjCoreErrorErrorMessageFactory;

@interface OrgAssertjCoreErrorShouldNotExist : OrgAssertjCoreErrorBasicErrorMessageFactory

#pragma mark Public

+ (id<OrgAssertjCoreErrorErrorMessageFactory>)shouldNotExistWithJavaIoFile:(JavaIoFile *)actual;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgAssertjCoreErrorShouldNotExist)

FOUNDATION_EXPORT id<OrgAssertjCoreErrorErrorMessageFactory> OrgAssertjCoreErrorShouldNotExist_shouldNotExistWithJavaIoFile_(JavaIoFile *actual);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreErrorShouldNotExist)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreErrorShouldNotExist")
