//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreErrorShouldHaveRootCauseInstance")
#ifdef RESTRICT_OrgAssertjCoreErrorShouldHaveRootCauseInstance
#define INCLUDE_ALL_OrgAssertjCoreErrorShouldHaveRootCauseInstance 0
#else
#define INCLUDE_ALL_OrgAssertjCoreErrorShouldHaveRootCauseInstance 1
#endif
#undef RESTRICT_OrgAssertjCoreErrorShouldHaveRootCauseInstance

#if !defined (OrgAssertjCoreErrorShouldHaveRootCauseInstance_) && (INCLUDE_ALL_OrgAssertjCoreErrorShouldHaveRootCauseInstance || defined(INCLUDE_OrgAssertjCoreErrorShouldHaveRootCauseInstance))
#define OrgAssertjCoreErrorShouldHaveRootCauseInstance_

#define RESTRICT_OrgAssertjCoreErrorBasicErrorMessageFactory 1
#define INCLUDE_OrgAssertjCoreErrorBasicErrorMessageFactory 1
#include "OrgAssertjCoreErrorBasicErrorMessageFactory.h"

@class IOSClass;
@protocol OrgAssertjCoreErrorErrorMessageFactory;

@interface OrgAssertjCoreErrorShouldHaveRootCauseInstance : OrgAssertjCoreErrorBasicErrorMessageFactory

#pragma mark Public

+ (id<OrgAssertjCoreErrorErrorMessageFactory>)shouldHaveRootCauseInstanceWithNSException:(NSException *)actual
                                                                            withIOSClass:(IOSClass *)expectedCauseType;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgAssertjCoreErrorShouldHaveRootCauseInstance)

FOUNDATION_EXPORT id<OrgAssertjCoreErrorErrorMessageFactory> OrgAssertjCoreErrorShouldHaveRootCauseInstance_shouldHaveRootCauseInstanceWithNSException_withIOSClass_(NSException *actual, IOSClass *expectedCauseType);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreErrorShouldHaveRootCauseInstance)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreErrorShouldHaveRootCauseInstance")
