//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreErrorShouldBeDirectory")
#ifdef RESTRICT_OrgAssertjCoreErrorShouldBeDirectory
#define INCLUDE_ALL_OrgAssertjCoreErrorShouldBeDirectory 0
#else
#define INCLUDE_ALL_OrgAssertjCoreErrorShouldBeDirectory 1
#endif
#undef RESTRICT_OrgAssertjCoreErrorShouldBeDirectory

#if !defined (OrgAssertjCoreErrorShouldBeDirectory_) && (INCLUDE_ALL_OrgAssertjCoreErrorShouldBeDirectory || defined(INCLUDE_OrgAssertjCoreErrorShouldBeDirectory))
#define OrgAssertjCoreErrorShouldBeDirectory_

#define RESTRICT_OrgAssertjCoreErrorBasicErrorMessageFactory 1
#define INCLUDE_OrgAssertjCoreErrorBasicErrorMessageFactory 1
#include "OrgAssertjCoreErrorBasicErrorMessageFactory.h"

@class JavaIoFile;
@protocol OrgAssertjCoreErrorErrorMessageFactory;

@interface OrgAssertjCoreErrorShouldBeDirectory : OrgAssertjCoreErrorBasicErrorMessageFactory

#pragma mark Public

+ (id<OrgAssertjCoreErrorErrorMessageFactory>)shouldBeDirectoryWithJavaIoFile:(JavaIoFile *)actual;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgAssertjCoreErrorShouldBeDirectory)

FOUNDATION_EXPORT id<OrgAssertjCoreErrorErrorMessageFactory> OrgAssertjCoreErrorShouldBeDirectory_shouldBeDirectoryWithJavaIoFile_(JavaIoFile *actual);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreErrorShouldBeDirectory)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreErrorShouldBeDirectory")
