//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RetrofitMimeMimeHelper")
#ifdef RESTRICT_RetrofitMimeMimeHelper
#define INCLUDE_ALL_RetrofitMimeMimeHelper 0
#else
#define INCLUDE_ALL_RetrofitMimeMimeHelper 1
#endif
#undef RESTRICT_RetrofitMimeMimeHelper

#if !defined (RetrofitMimeMimeHelper_) && (INCLUDE_ALL_RetrofitMimeMimeHelper || defined(INCLUDE_RetrofitMimeMimeHelper))
#define RetrofitMimeMimeHelper_

@class RetrofitMimeMultipartTypedOutput;
@protocol JavaUtilList;

@interface RetrofitMimeMimeHelper : NSObject

#pragma mark Public

- (instancetype)init;

+ (id<JavaUtilList>)getPartsWithRetrofitMimeMultipartTypedOutput:(RetrofitMimeMultipartTypedOutput *)output;

+ (RetrofitMimeMultipartTypedOutput *)newMultipartWithNSString:(NSString *)boundary OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(RetrofitMimeMimeHelper)

FOUNDATION_EXPORT void RetrofitMimeMimeHelper_init(RetrofitMimeMimeHelper *self);

FOUNDATION_EXPORT RetrofitMimeMimeHelper *new_RetrofitMimeMimeHelper_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RetrofitMimeMimeHelper *create_RetrofitMimeMimeHelper_init();

FOUNDATION_EXPORT id<JavaUtilList> RetrofitMimeMimeHelper_getPartsWithRetrofitMimeMultipartTypedOutput_(RetrofitMimeMultipartTypedOutput *output);

FOUNDATION_EXPORT RetrofitMimeMultipartTypedOutput *RetrofitMimeMimeHelper_newMultipartWithNSString_(NSString *boundary);

J2OBJC_TYPE_LITERAL_HEADER(RetrofitMimeMimeHelper)

#endif

#pragma pop_macro("INCLUDE_ALL_RetrofitMimeMimeHelper")
