//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RetrofitRxSupportTest__MockSubscriber$Moxy")
#ifdef RESTRICT_RetrofitRxSupportTest__MockSubscriber$Moxy
#define INCLUDE_ALL_RetrofitRxSupportTest__MockSubscriber$Moxy 0
#else
#define INCLUDE_ALL_RetrofitRxSupportTest__MockSubscriber$Moxy 1
#endif
#undef RESTRICT_RetrofitRxSupportTest__MockSubscriber$Moxy

#if !defined (RetrofitRxSupportTest__MockSubscriber_Moxy_) && (INCLUDE_ALL_RetrofitRxSupportTest__MockSubscriber$Moxy || defined(INCLUDE_RetrofitRxSupportTest__MockSubscriber_Moxy))
#define RetrofitRxSupportTest__MockSubscriber_Moxy_

#define RESTRICT_RetrofitRxSupportTest 1
#define INCLUDE_RetrofitRxSupportTest_MockSubscriber 1
#include "RetrofitRxSupportTest.h"

@protocol JavaLangReflectInvocationHandler;

@interface RetrofitRxSupportTest__MockSubscriber_Moxy : RetrofitRxSupportTest_MockSubscriber {
 @public
  id<JavaLangReflectInvocationHandler> $__handler_;
}

#pragma mark Public

- (jboolean)isEqual:(id)arg0;

- (id<JavaLangReflectInvocationHandler>)getHandler;

- (NSUInteger)hash;

- (void)onCompleted;

- (void)onErrorWithNSException:(NSException *)e;

- (void)onNextWithId:(id)o;

- (void)setHandlerWithJavaLangReflectInvocationHandler:(id<JavaLangReflectInvocationHandler>)handler;

- (jboolean)super$equalsWithId:(id)arg0;

- (jint)super$hashCode;

- (void)super$onCompleted;

- (void)super$onErrorWithNSException:(NSException *)e;

- (void)super$onNextWithId:(id)o;

- (NSString *)super$toString;

- (NSString *)description;

#pragma mark Protected

- (id)java_clone;

- (id)super$clone;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(RetrofitRxSupportTest__MockSubscriber_Moxy)

J2OBJC_FIELD_SETTER(RetrofitRxSupportTest__MockSubscriber_Moxy, $__handler_, id<JavaLangReflectInvocationHandler>)

FOUNDATION_EXPORT void RetrofitRxSupportTest__MockSubscriber_Moxy_init(RetrofitRxSupportTest__MockSubscriber_Moxy *self);

FOUNDATION_EXPORT RetrofitRxSupportTest__MockSubscriber_Moxy *new_RetrofitRxSupportTest__MockSubscriber_Moxy_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RetrofitRxSupportTest__MockSubscriber_Moxy *create_RetrofitRxSupportTest__MockSubscriber_Moxy_init();

J2OBJC_TYPE_LITERAL_HEADER(RetrofitRxSupportTest__MockSubscriber_Moxy)

@compatibility_alias RetrofitRxSupportTest__MockSubscriber$Moxy RetrofitRxSupportTest__MockSubscriber_Moxy;

#endif

#pragma pop_macro("INCLUDE_ALL_RetrofitRxSupportTest__MockSubscriber$Moxy")
