//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/api/BigDecimalAssert.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "OrgAssertjCoreApiAbstractBigDecimalAssert.h"
#include "OrgAssertjCoreApiBigDecimalAssert.h"
#include "java/math/BigDecimal.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@implementation OrgAssertjCoreApiBigDecimalAssert

- (instancetype)initWithJavaMathBigDecimal:(JavaMathBigDecimal *)actual {
  OrgAssertjCoreApiBigDecimalAssert_initWithJavaMathBigDecimal_(self, actual);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaMathBigDecimal:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LJavaMathBigDecimal;", "Lorg/assertj/core/api/AbstractBigDecimalAssert<Lorg/assertj/core/api/BigDecimalAssert;>;" };
  static const J2ObjcClassInfo _OrgAssertjCoreApiBigDecimalAssert = { "BigDecimalAssert", "org.assertj.core.api", ptrTable, methods, NULL, 7, 0x1, 1, 0, -1, -1, -1, 1, -1 };
  return &_OrgAssertjCoreApiBigDecimalAssert;
}

@end

void OrgAssertjCoreApiBigDecimalAssert_initWithJavaMathBigDecimal_(OrgAssertjCoreApiBigDecimalAssert *self, JavaMathBigDecimal *actual) {
  OrgAssertjCoreApiAbstractBigDecimalAssert_initWithJavaMathBigDecimal_withIOSClass_(self, actual, OrgAssertjCoreApiBigDecimalAssert_class_());
}

OrgAssertjCoreApiBigDecimalAssert *new_OrgAssertjCoreApiBigDecimalAssert_initWithJavaMathBigDecimal_(JavaMathBigDecimal *actual) {
  J2OBJC_NEW_IMPL(OrgAssertjCoreApiBigDecimalAssert, initWithJavaMathBigDecimal_, actual)
}

OrgAssertjCoreApiBigDecimalAssert *create_OrgAssertjCoreApiBigDecimalAssert_initWithJavaMathBigDecimal_(JavaMathBigDecimal *actual) {
  J2OBJC_CREATE_IMPL(OrgAssertjCoreApiBigDecimalAssert, initWithJavaMathBigDecimal_, actual)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgAssertjCoreApiBigDecimalAssert)
