//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/internal/ObjectArrays.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreInternalObjectArrays")
#ifdef RESTRICT_OrgAssertjCoreInternalObjectArrays
#define INCLUDE_ALL_OrgAssertjCoreInternalObjectArrays 0
#else
#define INCLUDE_ALL_OrgAssertjCoreInternalObjectArrays 1
#endif
#undef RESTRICT_OrgAssertjCoreInternalObjectArrays

#if !defined (OrgAssertjCoreInternalObjectArrays_) && (INCLUDE_ALL_OrgAssertjCoreInternalObjectArrays || defined(INCLUDE_OrgAssertjCoreInternalObjectArrays))
#define OrgAssertjCoreInternalObjectArrays_

@class IOSClass;
@class IOSObjectArray;
@class OrgAssertjCoreApiCondition;
@class OrgAssertjCoreDataIndex;
@class OrgAssertjCoreInternalConditions;
@class OrgAssertjCoreInternalFailures;
@protocol JavaLangIterable;
@protocol JavaUtilComparator;
@protocol OrgAssertjCoreApiAssertionInfo;
@protocol OrgAssertjCoreInternalComparisonStrategy;

@interface OrgAssertjCoreInternalObjectArrays : NSObject {
 @public
  OrgAssertjCoreInternalFailures *failures_;
  OrgAssertjCoreInternalConditions *conditions_;
}

#pragma mark Public

- (instancetype)initWithOrgAssertjCoreInternalComparisonStrategy:(id<OrgAssertjCoreInternalComparisonStrategy>)comparisonStrategy;

- (void)assertAreWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                  withNSObjectArray:(IOSObjectArray *)actual
                     withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertAreAtLeastWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                         withNSObjectArray:(IOSObjectArray *)actual
                                                   withInt:(jint)n
                            withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertAreAtMostWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                        withNSObjectArray:(IOSObjectArray *)actual
                                                  withInt:(jint)n
                           withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertAreExactlyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                         withNSObjectArray:(IOSObjectArray *)actual
                                                   withInt:(jint)n
                            withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertAreNotWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                     withNSObjectArray:(IOSObjectArray *)actual
                        withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertContainsWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                       withNSObjectArray:(IOSObjectArray *)actual
                                                  withId:(id)value
                             withOrgAssertjCoreDataIndex:(OrgAssertjCoreDataIndex *)index;

- (void)assertContainsWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                       withNSObjectArray:(IOSObjectArray *)actual
                                       withNSObjectArray:(IOSObjectArray *)values;

- (void)assertContainsAllWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withNSObjectArray:(IOSObjectArray *)actual
                                       withJavaLangIterable:(id<JavaLangIterable>)other;

- (void)assertContainsNullWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                           withNSObjectArray:(IOSObjectArray *)actual;

- (void)assertContainsOnlyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                           withNSObjectArray:(IOSObjectArray *)actual
                                           withNSObjectArray:(IOSObjectArray *)values;

- (void)assertContainsOnlyOnceWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                               withNSObjectArray:(IOSObjectArray *)actual
                                               withNSObjectArray:(IOSObjectArray *)values;

- (void)assertContainsSequenceWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                               withNSObjectArray:(IOSObjectArray *)actual
                                               withNSObjectArray:(IOSObjectArray *)sequence;

- (void)assertContainsSubsequenceWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                  withNSObjectArray:(IOSObjectArray *)actual
                                                  withNSObjectArray:(IOSObjectArray *)subsequence;

- (void)assertDoesNotContainWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                             withNSObjectArray:(IOSObjectArray *)actual
                                                        withId:(id)value
                                   withOrgAssertjCoreDataIndex:(OrgAssertjCoreDataIndex *)index;

- (void)assertDoesNotContainWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                             withNSObjectArray:(IOSObjectArray *)actual
                                             withNSObjectArray:(IOSObjectArray *)values;

- (void)assertDoesNotContainNullWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                 withNSObjectArray:(IOSObjectArray *)actual;

- (void)assertDoesNotHaveDuplicatesWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                    withNSObjectArray:(IOSObjectArray *)actual;

- (void)assertDoNotHaveWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                        withNSObjectArray:(IOSObjectArray *)actual
                           withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertEmptyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                    withNSObjectArray:(IOSObjectArray *)actual;

- (void)assertEndsWithWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                       withNSObjectArray:(IOSObjectArray *)actual
                                       withNSObjectArray:(IOSObjectArray *)sequence;

- (void)assertHasAtLeastOneElementOfTypeWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                         withNSObjectArray:(IOSObjectArray *)actual
                                                              withIOSClass:(IOSClass *)type;

- (void)assertHasOnlyElementsOfTypeWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                    withNSObjectArray:(IOSObjectArray *)actual
                                                         withIOSClass:(IOSClass *)type;

- (void)assertHasSameSizeAsWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                            withNSObjectArray:(IOSObjectArray *)actual
                                         withJavaLangIterable:(id<JavaLangIterable>)other;

- (void)assertHasSameSizeAsWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                            withNSObjectArray:(IOSObjectArray *)actual
                                                       withId:(id)other;

- (void)assertHasSizeWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                      withNSObjectArray:(IOSObjectArray *)actual
                                                withInt:(jint)expectedSize;

- (void)assertHaveWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                   withNSObjectArray:(IOSObjectArray *)actual
                      withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertHaveAtLeastWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withNSObjectArray:(IOSObjectArray *)actual
                                                    withInt:(jint)times
                             withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertHaveAtMostWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                         withNSObjectArray:(IOSObjectArray *)actual
                                                   withInt:(jint)times
                            withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertHaveExactlyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withNSObjectArray:(IOSObjectArray *)actual
                                                    withInt:(jint)times
                             withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition;

- (void)assertIsSortedWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                       withNSObjectArray:(IOSObjectArray *)actual;

- (void)assertIsSortedAccordingToComparatorWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                            withNSObjectArray:(IOSObjectArray *)actual
                                                       withJavaUtilComparator:(id<JavaUtilComparator>)comparator;

- (void)assertNotEmptyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                       withNSObjectArray:(IOSObjectArray *)actual;

- (void)assertNullOrEmptyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withNSObjectArray:(IOSObjectArray *)actual;

- (void)assertStartsWithWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                         withNSObjectArray:(IOSObjectArray *)actual
                                         withNSObjectArray:(IOSObjectArray *)sequence;

- (id<JavaUtilComparator>)getComparator;

+ (OrgAssertjCoreInternalObjectArrays *)instance;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(OrgAssertjCoreInternalObjectArrays)

J2OBJC_FIELD_SETTER(OrgAssertjCoreInternalObjectArrays, failures_, OrgAssertjCoreInternalFailures *)
J2OBJC_FIELD_SETTER(OrgAssertjCoreInternalObjectArrays, conditions_, OrgAssertjCoreInternalConditions *)

FOUNDATION_EXPORT OrgAssertjCoreInternalObjectArrays *OrgAssertjCoreInternalObjectArrays_instance();

FOUNDATION_EXPORT void OrgAssertjCoreInternalObjectArrays_init(OrgAssertjCoreInternalObjectArrays *self);

FOUNDATION_EXPORT OrgAssertjCoreInternalObjectArrays *new_OrgAssertjCoreInternalObjectArrays_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCoreInternalObjectArrays *create_OrgAssertjCoreInternalObjectArrays_init();

FOUNDATION_EXPORT void OrgAssertjCoreInternalObjectArrays_initWithOrgAssertjCoreInternalComparisonStrategy_(OrgAssertjCoreInternalObjectArrays *self, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

FOUNDATION_EXPORT OrgAssertjCoreInternalObjectArrays *new_OrgAssertjCoreInternalObjectArrays_initWithOrgAssertjCoreInternalComparisonStrategy_(id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCoreInternalObjectArrays *create_OrgAssertjCoreInternalObjectArrays_initWithOrgAssertjCoreInternalComparisonStrategy_(id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreInternalObjectArrays)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreInternalObjectArrays")
