//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/api/AbstractShortAssert.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreApiAbstractShortAssert")
#ifdef RESTRICT_OrgAssertjCoreApiAbstractShortAssert
#define INCLUDE_ALL_OrgAssertjCoreApiAbstractShortAssert 0
#else
#define INCLUDE_ALL_OrgAssertjCoreApiAbstractShortAssert 1
#endif
#undef RESTRICT_OrgAssertjCoreApiAbstractShortAssert

#if !defined (OrgAssertjCoreApiAbstractShortAssert_) && (INCLUDE_ALL_OrgAssertjCoreApiAbstractShortAssert || defined(INCLUDE_OrgAssertjCoreApiAbstractShortAssert))
#define OrgAssertjCoreApiAbstractShortAssert_

#define RESTRICT_OrgAssertjCoreApiAbstractComparableAssert 1
#define INCLUDE_OrgAssertjCoreApiAbstractComparableAssert 1
#include "OrgAssertjCoreApiAbstractComparableAssert.h"

#define RESTRICT_OrgAssertjCoreApiNumberAssert 1
#define INCLUDE_OrgAssertjCoreApiNumberAssert 1
#include "OrgAssertjCoreApiNumberAssert.h"

@class IOSClass;
@class IOSObjectArray;
@class JavaLangShort;
@class OrgAssertjCoreApiCondition;
@class OrgAssertjCoreDescriptionDescription;
@class OrgAssertjCoreInternalShorts;
@protocol JavaLangIterable;
@protocol JavaUtilComparator;

@interface OrgAssertjCoreApiAbstractShortAssert : OrgAssertjCoreApiAbstractComparableAssert < OrgAssertjCoreApiNumberAssert > {
 @public
  OrgAssertjCoreInternalShorts *shorts_;
}

#pragma mark Public

- (OrgAssertjCoreApiAbstractShortAssert *)asWithNSString:(NSString *)arg0
                                       withNSObjectArray:(IOSObjectArray *)arg1;

- (OrgAssertjCoreApiAbstractShortAssert *)asWithOrgAssertjCoreDescriptionDescription:(OrgAssertjCoreDescriptionDescription *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)describedAsWithNSString:(NSString *)arg0
                                                withNSObjectArray:(IOSObjectArray *)arg1;

- (OrgAssertjCoreApiAbstractShortAssert *)describedAsWithOrgAssertjCoreDescriptionDescription:(OrgAssertjCoreDescriptionDescription *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)doesNotHaveSameClassAsWithId:(id)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)doesNotHaveWithOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)hasSameClassAsWithId:(id)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)hasWithOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)inBinary;

- (OrgAssertjCoreApiAbstractShortAssert *)inHexadecimal;

- (OrgAssertjCoreApiAbstractShortAssert *)isBetweenWithNSNumber:(JavaLangShort *)start
                                                   withNSNumber:(JavaLangShort *)end;

- (OrgAssertjCoreApiAbstractShortAssert *)isEqualToWithShort:(jshort)expected;

- (OrgAssertjCoreApiAbstractShortAssert *)isEqualToWithId:(id)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isExactlyInstanceOfWithIOSClass:(IOSClass *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isGreaterThanWithShort:(jshort)other;

- (OrgAssertjCoreApiAbstractShortAssert *)isGreaterThanOrEqualToWithShort:(jshort)other;

- (OrgAssertjCoreApiAbstractShortAssert *)isGreaterThanOrEqualToWithJavaLangComparable:(JavaLangShort *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isGreaterThanWithJavaLangComparable:(JavaLangShort *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isInstanceOfAnyWithIOSClassArray:(IOSObjectArray *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isInstanceOfWithIOSClass:(IOSClass *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isInWithJavaLangIterable:(id<JavaLangIterable>)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isInWithNSObjectArray:(IOSObjectArray *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isLessThanWithShort:(jshort)other;

- (OrgAssertjCoreApiAbstractShortAssert *)isLessThanOrEqualToWithShort:(jshort)other;

- (OrgAssertjCoreApiAbstractShortAssert *)isLessThanOrEqualToWithJavaLangComparable:(JavaLangShort *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isLessThanWithJavaLangComparable:(JavaLangShort *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNegative;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotEqualToWithShort:(jshort)other;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotEqualToWithId:(id)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotExactlyInstanceOfWithIOSClass:(IOSClass *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotInstanceOfAnyWithIOSClassArray:(IOSObjectArray *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotInstanceOfWithIOSClass:(IOSClass *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotInWithJavaLangIterable:(id<JavaLangIterable>)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotInWithNSObjectArray:(IOSObjectArray *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotNegative;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotNull;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotOfAnyClassInWithIOSClassArray:(IOSObjectArray *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotPositive;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotSameAsWithId:(id)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotWithOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isNotZero;

- (OrgAssertjCoreApiAbstractShortAssert *)isOfAnyClassInWithIOSClassArray:(IOSObjectArray *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isPositive;

- (OrgAssertjCoreApiAbstractShortAssert *)isSameAsWithId:(id)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isStrictlyBetweenWithNSNumber:(JavaLangShort *)start
                                                           withNSNumber:(JavaLangShort *)end;

- (OrgAssertjCoreApiAbstractShortAssert *)isWithOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)arg0;

- (OrgAssertjCoreApiAbstractShortAssert *)isZero;

- (OrgAssertjCoreApiAbstractShortAssert *)overridingErrorMessageWithNSString:(NSString *)arg0
                                                           withNSObjectArray:(IOSObjectArray *)arg1;

- (OrgAssertjCoreApiAbstractShortAssert *)usingComparatorWithJavaUtilComparator:(id<JavaUtilComparator>)customComparator;

- (OrgAssertjCoreApiAbstractShortAssert *)usingDefaultComparator;

#pragma mark Protected

- (instancetype)initWithJavaLangShort:(JavaLangShort *)actual
                         withIOSClass:(IOSClass *)selfType;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgAssertjCoreApiAbstractShortAssert)

J2OBJC_FIELD_SETTER(OrgAssertjCoreApiAbstractShortAssert, shorts_, OrgAssertjCoreInternalShorts *)

FOUNDATION_EXPORT void OrgAssertjCoreApiAbstractShortAssert_initWithJavaLangShort_withIOSClass_(OrgAssertjCoreApiAbstractShortAssert *self, JavaLangShort *actual, IOSClass *selfType);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreApiAbstractShortAssert)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreApiAbstractShortAssert")
