//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/api/IntegerAssert.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "OrgAssertjCoreApiAbstractIntegerAssert.h"
#include "OrgAssertjCoreApiIntegerAssert.h"
#include "java/lang/Integer.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@implementation OrgAssertjCoreApiIntegerAssert

- (instancetype)initWithJavaLangInteger:(JavaLangInteger *)actual {
  OrgAssertjCoreApiIntegerAssert_initWithJavaLangInteger_(self, actual);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x4, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaLangInteger:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LJavaLangInteger;", "Lorg/assertj/core/api/AbstractIntegerAssert<Lorg/assertj/core/api/IntegerAssert;>;" };
  static const J2ObjcClassInfo _OrgAssertjCoreApiIntegerAssert = { "IntegerAssert", "org.assertj.core.api", ptrTable, methods, NULL, 7, 0x1, 1, 0, -1, -1, -1, 1, -1 };
  return &_OrgAssertjCoreApiIntegerAssert;
}

@end

void OrgAssertjCoreApiIntegerAssert_initWithJavaLangInteger_(OrgAssertjCoreApiIntegerAssert *self, JavaLangInteger *actual) {
  OrgAssertjCoreApiAbstractIntegerAssert_initWithJavaLangInteger_withIOSClass_(self, actual, OrgAssertjCoreApiIntegerAssert_class_());
}

OrgAssertjCoreApiIntegerAssert *new_OrgAssertjCoreApiIntegerAssert_initWithJavaLangInteger_(JavaLangInteger *actual) {
  J2OBJC_NEW_IMPL(OrgAssertjCoreApiIntegerAssert, initWithJavaLangInteger_, actual)
}

OrgAssertjCoreApiIntegerAssert *create_OrgAssertjCoreApiIntegerAssert_initWithJavaLangInteger_(JavaLangInteger *actual) {
  J2OBJC_CREATE_IMPL(OrgAssertjCoreApiIntegerAssert, initWithJavaLangInteger_, actual)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgAssertjCoreApiIntegerAssert)
