//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/presentation/UnicodeRepresentation.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCorePresentationUnicodeRepresentation")
#ifdef RESTRICT_OrgAssertjCorePresentationUnicodeRepresentation
#define INCLUDE_ALL_OrgAssertjCorePresentationUnicodeRepresentation 0
#else
#define INCLUDE_ALL_OrgAssertjCorePresentationUnicodeRepresentation 1
#endif
#undef RESTRICT_OrgAssertjCorePresentationUnicodeRepresentation

#if !defined (OrgAssertjCorePresentationUnicodeRepresentation_) && (INCLUDE_ALL_OrgAssertjCorePresentationUnicodeRepresentation || defined(INCLUDE_OrgAssertjCorePresentationUnicodeRepresentation))
#define OrgAssertjCorePresentationUnicodeRepresentation_

#define RESTRICT_OrgAssertjCorePresentationRepresentation 1
#define INCLUDE_OrgAssertjCorePresentationRepresentation 1
#include "OrgAssertjCorePresentationRepresentation.h"

@interface OrgAssertjCorePresentationUnicodeRepresentation : NSObject < OrgAssertjCorePresentationRepresentation >

#pragma mark Public

- (instancetype)init;

- (NSString *)toStringOfWithId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgAssertjCorePresentationUnicodeRepresentation)

FOUNDATION_EXPORT void OrgAssertjCorePresentationUnicodeRepresentation_init(OrgAssertjCorePresentationUnicodeRepresentation *self);

FOUNDATION_EXPORT OrgAssertjCorePresentationUnicodeRepresentation *new_OrgAssertjCorePresentationUnicodeRepresentation_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCorePresentationUnicodeRepresentation *create_OrgAssertjCorePresentationUnicodeRepresentation_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCorePresentationUnicodeRepresentation)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCorePresentationUnicodeRepresentation")
