//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/internal/ShortArrays.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreInternalShortArrays")
#ifdef RESTRICT_OrgAssertjCoreInternalShortArrays
#define INCLUDE_ALL_OrgAssertjCoreInternalShortArrays 0
#else
#define INCLUDE_ALL_OrgAssertjCoreInternalShortArrays 1
#endif
#undef RESTRICT_OrgAssertjCoreInternalShortArrays

#if !defined (OrgAssertjCoreInternalShortArrays_) && (INCLUDE_ALL_OrgAssertjCoreInternalShortArrays || defined(INCLUDE_OrgAssertjCoreInternalShortArrays))
#define OrgAssertjCoreInternalShortArrays_

@class IOSObjectArray;
@class IOSShortArray;
@class OrgAssertjCoreDataIndex;
@class OrgAssertjCoreInternalFailures;
@protocol JavaLangIterable;
@protocol JavaUtilComparator;
@protocol OrgAssertjCoreApiAssertionInfo;
@protocol OrgAssertjCoreInternalComparisonStrategy;

@interface OrgAssertjCoreInternalShortArrays : NSObject {
 @public
  OrgAssertjCoreInternalFailures *failures_;
}

#pragma mark Public

- (instancetype)initWithOrgAssertjCoreInternalComparisonStrategy:(id<OrgAssertjCoreInternalComparisonStrategy>)comparisonStrategy;

- (void)assertContainsWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withShortArray:(IOSShortArray *)actual
                                               withShort:(jshort)value
                             withOrgAssertjCoreDataIndex:(OrgAssertjCoreDataIndex *)index;

- (void)assertContainsWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withShortArray:(IOSShortArray *)actual
                                          withShortArray:(IOSShortArray *)values;

- (void)assertContainsOnlyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                              withShortArray:(IOSShortArray *)actual
                                              withShortArray:(IOSShortArray *)values;

- (void)assertContainsOnlyOnceWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                  withShortArray:(IOSShortArray *)actual
                                                  withShortArray:(IOSShortArray *)values;

- (void)assertContainsSequenceWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                  withShortArray:(IOSShortArray *)actual
                                                  withShortArray:(IOSShortArray *)sequence;

- (void)assertContainsSubsequenceWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                     withShortArray:(IOSShortArray *)actual
                                                     withShortArray:(IOSShortArray *)subsequence;

- (void)assertDoesNotContainWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                withShortArray:(IOSShortArray *)actual
                                                     withShort:(jshort)value
                                   withOrgAssertjCoreDataIndex:(OrgAssertjCoreDataIndex *)index;

- (void)assertDoesNotContainWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                withShortArray:(IOSShortArray *)actual
                                                withShortArray:(IOSShortArray *)values;

- (void)assertDoesNotHaveDuplicatesWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                       withShortArray:(IOSShortArray *)actual;

- (void)assertEmptyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                       withShortArray:(IOSShortArray *)actual;

- (void)assertEndsWithWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withShortArray:(IOSShortArray *)actual
                                          withShortArray:(IOSShortArray *)sequence;

- (void)assertHasSameSizeAsWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                               withShortArray:(IOSShortArray *)actual
                                         withJavaLangIterable:(id<JavaLangIterable>)other;

- (void)assertHasSameSizeAsWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                               withShortArray:(IOSShortArray *)actual
                                            withNSObjectArray:(IOSObjectArray *)other;

- (void)assertHasSizeWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                         withShortArray:(IOSShortArray *)actual
                                                withInt:(jint)expectedSize;

- (void)assertIsSortedWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withShortArray:(IOSShortArray *)actual;

- (void)assertIsSortedAccordingToComparatorWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                                               withShortArray:(IOSShortArray *)actual
                                                       withJavaUtilComparator:(id<JavaUtilComparator>)comparator;

- (void)assertNotEmptyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                          withShortArray:(IOSShortArray *)actual;

- (void)assertNullOrEmptyWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                             withShortArray:(IOSShortArray *)actual;

- (void)assertStartsWithWithOrgAssertjCoreApiAssertionInfo:(id<OrgAssertjCoreApiAssertionInfo>)info
                                            withShortArray:(IOSShortArray *)actual
                                            withShortArray:(IOSShortArray *)sequence;

- (id<JavaUtilComparator>)getComparator;

+ (OrgAssertjCoreInternalShortArrays *)instance;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(OrgAssertjCoreInternalShortArrays)

J2OBJC_FIELD_SETTER(OrgAssertjCoreInternalShortArrays, failures_, OrgAssertjCoreInternalFailures *)

FOUNDATION_EXPORT OrgAssertjCoreInternalShortArrays *OrgAssertjCoreInternalShortArrays_instance();

FOUNDATION_EXPORT void OrgAssertjCoreInternalShortArrays_init(OrgAssertjCoreInternalShortArrays *self);

FOUNDATION_EXPORT OrgAssertjCoreInternalShortArrays *new_OrgAssertjCoreInternalShortArrays_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCoreInternalShortArrays *create_OrgAssertjCoreInternalShortArrays_init();

FOUNDATION_EXPORT void OrgAssertjCoreInternalShortArrays_initWithOrgAssertjCoreInternalComparisonStrategy_(OrgAssertjCoreInternalShortArrays *self, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

FOUNDATION_EXPORT OrgAssertjCoreInternalShortArrays *new_OrgAssertjCoreInternalShortArrays_initWithOrgAssertjCoreInternalComparisonStrategy_(id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCoreInternalShortArrays *create_OrgAssertjCoreInternalShortArrays_initWithOrgAssertjCoreInternalComparisonStrategy_(id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreInternalShortArrays)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreInternalShortArrays")
