//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/error/ShouldBeBeforeOrEqualsTo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo")
#ifdef RESTRICT_OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo
#define INCLUDE_ALL_OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo 0
#else
#define INCLUDE_ALL_OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo 1
#endif
#undef RESTRICT_OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo

#if !defined (OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo_) && (INCLUDE_ALL_OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo || defined(INCLUDE_OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo))
#define OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo_

#define RESTRICT_OrgAssertjCoreErrorBasicErrorMessageFactory 1
#define INCLUDE_OrgAssertjCoreErrorBasicErrorMessageFactory 1
#include "OrgAssertjCoreErrorBasicErrorMessageFactory.h"

@class JavaUtilDate;
@protocol OrgAssertjCoreErrorErrorMessageFactory;
@protocol OrgAssertjCoreInternalComparisonStrategy;

@interface OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo : OrgAssertjCoreErrorBasicErrorMessageFactory

#pragma mark Public

+ (id<OrgAssertjCoreErrorErrorMessageFactory>)shouldBeBeforeOrEqualsToWithJavaUtilDate:(JavaUtilDate *)actual
                                                                      withJavaUtilDate:(JavaUtilDate *)other;

+ (id<OrgAssertjCoreErrorErrorMessageFactory>)shouldBeBeforeOrEqualsToWithJavaUtilDate:(JavaUtilDate *)actual
                                                                      withJavaUtilDate:(JavaUtilDate *)other
                                          withOrgAssertjCoreInternalComparisonStrategy:(id<OrgAssertjCoreInternalComparisonStrategy>)comparisonStrategy;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo)

FOUNDATION_EXPORT id<OrgAssertjCoreErrorErrorMessageFactory> OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo_shouldBeBeforeOrEqualsToWithJavaUtilDate_withJavaUtilDate_withOrgAssertjCoreInternalComparisonStrategy_(JavaUtilDate *actual, JavaUtilDate *other, id<OrgAssertjCoreInternalComparisonStrategy> comparisonStrategy);

FOUNDATION_EXPORT id<OrgAssertjCoreErrorErrorMessageFactory> OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo_shouldBeBeforeOrEqualsToWithJavaUtilDate_withJavaUtilDate_(JavaUtilDate *actual, JavaUtilDate *other);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreErrorShouldBeBeforeOrEqualsTo")
