//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/extractor/Extractors.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgAssertjCoreExtractorExtractors")
#ifdef RESTRICT_OrgAssertjCoreExtractorExtractors
#define INCLUDE_ALL_OrgAssertjCoreExtractorExtractors 0
#else
#define INCLUDE_ALL_OrgAssertjCoreExtractorExtractors 1
#endif
#undef RESTRICT_OrgAssertjCoreExtractorExtractors

#if !defined (OrgAssertjCoreExtractorExtractors_) && (INCLUDE_ALL_OrgAssertjCoreExtractorExtractors || defined(INCLUDE_OrgAssertjCoreExtractorExtractors))
#define OrgAssertjCoreExtractorExtractors_

@class IOSObjectArray;
@protocol OrgAssertjCoreApiIterableExtractor;

@interface OrgAssertjCoreExtractorExtractors : NSObject

#pragma mark Public

- (instancetype)init;

+ (id<OrgAssertjCoreApiIterableExtractor>)byNameWithNSString:(NSString *)fieldOrProperty;

+ (id<OrgAssertjCoreApiIterableExtractor>)byNameWithNSStringArray:(IOSObjectArray *)fieldsOrProperties;

+ (id<OrgAssertjCoreApiIterableExtractor>)resultOfWithNSString:(NSString *)methodName;

+ (id<OrgAssertjCoreApiIterableExtractor>)toStringMethod;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgAssertjCoreExtractorExtractors)

FOUNDATION_EXPORT void OrgAssertjCoreExtractorExtractors_init(OrgAssertjCoreExtractorExtractors *self);

FOUNDATION_EXPORT OrgAssertjCoreExtractorExtractors *new_OrgAssertjCoreExtractorExtractors_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgAssertjCoreExtractorExtractors *create_OrgAssertjCoreExtractorExtractors_init();

FOUNDATION_EXPORT id<OrgAssertjCoreApiIterableExtractor> OrgAssertjCoreExtractorExtractors_toStringMethod();

FOUNDATION_EXPORT id<OrgAssertjCoreApiIterableExtractor> OrgAssertjCoreExtractorExtractors_byNameWithNSString_(NSString *fieldOrProperty);

FOUNDATION_EXPORT id<OrgAssertjCoreApiIterableExtractor> OrgAssertjCoreExtractorExtractors_byNameWithNSStringArray_(IOSObjectArray *fieldsOrProperties);

FOUNDATION_EXPORT id<OrgAssertjCoreApiIterableExtractor> OrgAssertjCoreExtractorExtractors_resultOfWithNSString_(NSString *methodName);

J2OBJC_TYPE_LITERAL_HEADER(OrgAssertjCoreExtractorExtractors)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgAssertjCoreExtractorExtractors")
