//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/org/assertj/core/error/ConditionAndGroupGenericParameterTypeShouldBeTheSame.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "OrgAssertjCoreApiCondition.h"
#include "OrgAssertjCoreErrorBasicErrorMessageFactory.h"
#include "OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame.h"
#include "OrgAssertjCoreErrorErrorMessageFactory.h"

@implementation OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame

- (instancetype)initWithId:(id)actual
withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition {
  OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame_initWithId_withOrgAssertjCoreApiCondition_(self, actual, condition);
  return self;
}

+ (id<OrgAssertjCoreErrorErrorMessageFactory>)shouldBeSameGenericBetweenIterableAndConditionWithId:(id)actual
                                                                    withOrgAssertjCoreApiCondition:(OrgAssertjCoreApiCondition *)condition {
  return OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame_shouldBeSameGenericBetweenIterableAndConditionWithId_withOrgAssertjCoreApiCondition_(actual, condition);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "LOrgAssertjCoreErrorErrorMessageFactory;", 0x9, 2, 0, -1, 3, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithId:withOrgAssertjCoreApiCondition:);
  methods[1].selector = @selector(shouldBeSameGenericBetweenIterableAndConditionWithId:withOrgAssertjCoreApiCondition:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSObject;LOrgAssertjCoreApiCondition;", "(Ljava/lang/Object;Lorg/assertj/core/api/Condition<*>;)V", "shouldBeSameGenericBetweenIterableAndCondition", "(Ljava/lang/Object;Lorg/assertj/core/api/Condition<*>;)Lorg/assertj/core/error/ErrorMessageFactory;" };
  static const J2ObjcClassInfo _OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame = { "ConditionAndGroupGenericParameterTypeShouldBeTheSame", "org.assertj.core.error", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame;
}

@end

void OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame_initWithId_withOrgAssertjCoreApiCondition_(OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame *self, id actual, OrgAssertjCoreApiCondition *condition) {
  OrgAssertjCoreErrorBasicErrorMessageFactory_initWithNSString_withNSObjectArray_(self, @"\nExpecting: <%s> have the same generic type as condition <%s>", [IOSObjectArray arrayWithObjects:(id[]){ actual, condition } count:2 type:NSObject_class_()]);
}

OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame *new_OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame_initWithId_withOrgAssertjCoreApiCondition_(id actual, OrgAssertjCoreApiCondition *condition) {
  J2OBJC_NEW_IMPL(OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame, initWithId_withOrgAssertjCoreApiCondition_, actual, condition)
}

OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame *create_OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame_initWithId_withOrgAssertjCoreApiCondition_(id actual, OrgAssertjCoreApiCondition *condition) {
  J2OBJC_CREATE_IMPL(OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame, initWithId_withOrgAssertjCoreApiCondition_, actual, condition)
}

id<OrgAssertjCoreErrorErrorMessageFactory> OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame_shouldBeSameGenericBetweenIterableAndConditionWithId_withOrgAssertjCoreApiCondition_(id actual, OrgAssertjCoreApiCondition *condition) {
  OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame_initialize();
  return create_OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame_initWithId_withOrgAssertjCoreApiCondition_(actual, condition);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgAssertjCoreErrorConditionAndGroupGenericParameterTypeShouldBeTheSame)
