//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/kgalligan/devel-doppl/retrofit-doppl/retrofit/src/test/java/retrofit/RestAdapterTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RetrofitRestAdapterTest")
#ifdef RESTRICT_RetrofitRestAdapterTest
#define INCLUDE_ALL_RetrofitRestAdapterTest 0
#else
#define INCLUDE_ALL_RetrofitRestAdapterTest 1
#endif
#undef RESTRICT_RetrofitRestAdapterTest

#if !defined (RetrofitRestAdapterTest_) && (INCLUDE_ALL_RetrofitRestAdapterTest || defined(INCLUDE_RetrofitRestAdapterTest))
#define RetrofitRestAdapterTest_

@interface RetrofitRestAdapterTest : NSObject

#pragma mark Public

- (instancetype)init;

- (void)asynchronousUsesExecutors;

- (void)bodyTypedInputExceptionThrowsNetworkError;

- (void)clientExceptionThrowsNetworkError;

- (void)closeInputStream;

- (void)errorAsync;

- (void)errorResponseThrowsHttpError;

- (void)getAsync;

- (void)getResponseDirectly;

- (void)getResponseDirectlyAsync;

- (void)interfaceWithExtendIsNotSupported;

- (void)logErrorRequestResponseFullWhenMimeTypeMissing;

- (void)logErrorRequestResponseFullWhenResponseBodyAbsent;

- (void)logRequestResponseBasic;

- (void)logRequestResponseHeaders;

- (void)logRequestResponseHeadersAndArgs;

- (void)logSuccessfulRequestResponseFullWhenMimeTypeMissing;

- (void)logSuccessfulRequestResponseFullWhenResponseBodyAbsent;

- (void)logSuccessfulRequestResponseFullWhenResponseBodyPresent;

- (void)logSuccessfulRequestResponseHeadersAndArgsWhenResponseBodyAbsent;

- (void)logSuccessfulRequestResponseHeadersAndArgsWhenResponseBodyPresent;

- (void)malformedResponseThrowsConversionException;

- (void)objectMethodsStillWork;

- (void)observableCallsOnError;

- (void)observableCallsOnNext;

- (void)observableHandlesParams;

- (void)observableUsesHttpExecutor;

- (void)profilerObjectPassThrough;

- (void)setUp;

- (void)streamingResponse;

- (void)successfulRequestResponseWhenMimeTypeMissing;

- (void)synchronousDoesNotUseExecutors;

- (void)unexpectedExceptionThrows;

@end

J2OBJC_STATIC_INIT(RetrofitRestAdapterTest)

FOUNDATION_EXPORT void RetrofitRestAdapterTest_init(RetrofitRestAdapterTest *self);

FOUNDATION_EXPORT RetrofitRestAdapterTest *new_RetrofitRestAdapterTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RetrofitRestAdapterTest *create_RetrofitRestAdapterTest_init();

J2OBJC_TYPE_LITERAL_HEADER(RetrofitRestAdapterTest)

#endif

#pragma pop_macro("INCLUDE_ALL_RetrofitRestAdapterTest")
